version: '3'
services:
  database:
    image: mysql:latest
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
